version: '3'
services:
    app:
      build: .
      container_name: app
      entrypoint: >
        dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 20s &&
        php-fpm     
      environment:
        - DB_CONNECTION=db
        - DB_HOST=db
        - DB_PORT=3306
        - DB_DATABASE=laravel
        - DB_USERNAME=laravel
        - DB_PASSWORD=root
      volumes:
        - .:/var/www     
      networks:
        - app-network
      depends_on:
        - db
        - redis

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        image: nginx:latest
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-network

    db:
        image: mysql:latest
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        environment:
            - DB_HOST=db
            - DB_DATABASE=laravelaaaaaaaa
            - DB_USERNAME=laravel
            - DB_PASSWORD=root
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        networks:
            - app-network

    redis:
        image: redis:latest
        expose:
            - "6379"
        container_name: redis
        restart: always
        networks:
            - app-network

networks:
   app-network:
        driver: bridge